### ISSUE TITLE
Todo list:

### ISSUE THREAD

**Issue by spking** [spking/p-skitakall#1]
__List of project goals__

- [ ] Finalise functionality within Python Shell
- [ ] Start work on GUI with tkinter or pygame
- [ ] Finalise functionality in executable form
- [ ] Develop local multiplayer
- [ ] Develop online multiplayer
